### ISSUE TITLE
How to override default settings?

### ISSUE THREAD

**Issue by anjildhamala** [RickCraig/node-tiff-to-png#11]
I just have two questions.
1. Is there a way to not generate .DS_Store folder?
2. Under the target location, I don't want my images to be in another 'filename' folder. As in, if my filename is test.tiff, it puts the generated images under test folder. How can I stop this behavior?

**Comment by RickCraig** [comment]
Hi,

1. Is there a .DS_Store folder in the source folder, is one just being generated out of the blue before you look at the target folder in finder?
2. When calling convert or convertOne you can pass an empty string `''` as the second argument. This will save the files in place. [Docs](https://github.com/RickCraig/node-tiff-to-png#save-location)

**Comment by anjildhamala** [comment]
Thank you for replying. The .DS_Store was Mac generated file. Not sure why Mac does that but it was safe to delete it.
