### ISSUE TITLE
Parametre non valide - -scene

### ISSUE THREAD

**Issue by Syno0** [RickCraig/node-tiff-to-png#8]
Hello,

I need to convert a tif file into png but when I try I have an error that I don't understand : 
`[ { target: 'D:\\Bureau\\newmips\\newmips\\workspace\\1\\routes\\..\\stuff\\done/1',
    error:
     { Error: Command failed: convert D:\Bureau\newmips\newmips\workspace\1\routes\..\stuff\1.tif -scene 1 D:\Bureau\new
orkspace\1\routes\..\stuff\done/1/page%d.png
     Param�tre non valide - -scene

         at ChildProcess.exithandler (child_process.js:206:12)
         at emitTwo (events.js:106:13)
         at ChildProcess.emit (events.js:191:7)
         at maybeClose (internal/child_process.js:877:16)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
       killed: false,
       code: 4,
       signal: null,
       cmd: 'convert D:\\Bureau\\newmips\\newmips\\workspace\\1\\routes\\..\\stuff\\1.tif -scene 1 D:\\Bureau\\newmips\\
pace\\1\\routes\\..\\stuff\\done/1/page%d.png' } } ]
`

Here is my code : 
`var options = {
        logLevel: 1
    };

    var converter = new ConvertTiff(options);

    var tiffs = [
        __dirname + "\\..\\stuff\\1.tif"
    ];
    var location =  __dirname + "\\..\\stuff\\done";

    converter.complete = function(errors, total){
        console.log(errors);
    };

    converter.convertArray(tiffs, location);`

Thanks for the help

**Comment by SuDT** [comment]
**Same issue for me:**

`
node .\tiff-to-png.js
Started converting 2 TIFFs


  TON2_ASHENa (created)
    ✗ Conversion failed


  TON2_ASHENb (created)
    ✗ Conversion failed


  0 Converted.
  2 Failed.


./TON2_ASHENa
Error: Command failed: convert TON2_ASHENa.tif -scene 1 ./TON2_ASHENa/page%d.jpg
**Invalid Parameter - -scene**



./TON2_ASHENb
Error: Command failed: convert TON2_ASHENb.tif -scene 1 ./TON2_ASHENb/page%d.jpg
**Invalid Parameter - -scene**

`

**Comment by RickCraig** [comment]
Could you give me a few details:
- What operating system are you guys on?
- Does the tiff have multiple pages?
- Could you maybe get me a copy of a broken tiff?
- Also what version of Imagemagick do you have installed?

I can't replicate this locally, on 6.9.x.x or 7.0.x.x

**Comment by RickCraig** [comment]
I've decided to update the module to align it better with the new stuff like async/await (promises) and i'll add an option to omit scene from the command line as part of that update. That should solve this problem in the future.
